language: node_js
script: "node_modules/.bin/commitlint-travis && yarn lint && make test reporter=spec && make test-browser reporter=spec && make coverage cov-reporter=travis-cov"
sudo: required
branches:
  only:
    - master
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
matrix:
  include:
  - node_js: "stable"
    env: NODE_CACHE_BUST=stable
  - node_js: "12.21.0"
    env: NODE_CACHE_BUST=12.21.0
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
